travis:
  secure:
    BINSTAR_TOKEN: icjZybM61QTqOe5WDgHksYmoTMVIF0j+hfDI5W4RhdrHLLaMtW8Ls5c5SlImjjRcRLmchbcmD7aYs3Prw9uJ/Bv1hIeurP5yGoaZYOw0ayRFYWuAxudb/qh6lWE6iMUejkBz6plnuPtEUSXi3qlGFKpJadIww075khOqwqcThI3RMD18t4OaAek5wGeQzEAYmPocediwnQtrHFn3rq+Psx4EmYPxR+mqL1NpA/wOF4I8M33PUHoA0JRcO4mntxsDz8e/o3QNO8d1/GeFXqEH0qJHhcOZXzSjB88OJ6hvIIxonGtvBW5v/CoYmAHfn0DWgw0+t123yoj0LuEGCbQ4Rv15WcwS4iRVzfy9v6jonrcCZmDW4n13sAj11SVfPYpbXr6K0KShonQWhkDxO2EXi1XMgZem3Zq+ImAJocliqQr1RCxKFXxe+BXP27SdoThMQudAPuZY4ruqRQGKTs48Y7uuVCPEJ9k6AtqW4ScXtKQ+aTY/RvDLK6CT3qC+AA2IU3s9aQTYJjP4QxNSnsmyko6kfMhWadOE0P7lnDfWNghESq6uMIJnIIqKFfdC5V1oAZCpEVPoFgWrRv4hj1x9MqF+7pxv8dwl/X/Sg1GTFKfDH7rpN6/Uv4danxQqhXfdL1PGhqJdKLmUqWIRj6emMAuFo3UEoQ4siYDJRNY+XXM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
