travis:
  secure:
    BINSTAR_TOKEN: EUeXw87WsaGz6ZqB4/3WrtCAwD1hkuhJ93yXm+gxi5CXgF8478cu8t1xqsMBmHdrJ0zGS8DuNkUu8sBRXNKRTffVX2kH0CkxrmJgbDLsgsEu988w8kEMMZyfkYfWJYMpse1/Gq9ew52e0GnO4x8nbh9xaBBydPAPDAv/yaDebzbeDDtP+EV/ei3L9ymE5/mW13Xpx39C/hJLmatp3J62zVCtx7XcYOB0C6P1T3aggplYj9oh5HwLDgX9mojgC4bnh52WAY2i/FZi6ZFslO6B9SzvwO6vI8GrU44ZFR2hloxSritrJIoX3xdySwKtuZt/KkN1Zu7LRnWFy8Nf68+7CtnbXQ6+Os4gabxQTuJeesELrJKoobNXaJ2SMjRqLS8f+w5UVggQQmj27OfdQEQCk21hmpJNZ6xcbJSqzFvra3w7ELvvoAkt1XD0uIzm8ZjdS3b3ylLkLtBa2HU5lS4dMf4J9BMEMnBvQ74jo+Tnz9Df0IhPC8z7LsX/ISMKD+MKsdANr/RGUecSGEhp1dkA4Z8ffMBbWPnj2S6N1mqWzZC1tUsPG6Z49LZcJuI5O32FQAWad8grlbqU6O95FGAluNVDDxC5cqxI88BSFs5lDnTy4AhL/6miDFSylHE2p6nZxarPPh7BpgLir78FIvT7KmzzlYvgxzzlNLD+vSBLEwY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
